// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCEr6cJ1sDcna0P-mW0w1m2W1w5lPLKdak',
    appId: '1:1014566436831:web:3011d989e0a254527d8e6a',
    messagingSenderId: '1014566436831',
    projectId: 'ecat-preparation',
    authDomain: 'ecat-preparation.firebaseapp.com',
    databaseURL: 'https://ecat-preparation-default-rtdb.firebaseio.com',
    storageBucket: 'ecat-preparation.appspot.com',
    measurementId: 'G-G0EYQ0GG4W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCobfeVJeiwVqez9CYPKS5zKnZsRTTpkNk',
    appId: '1:1014566436831:android:7223bab5760105767d8e6a',
    messagingSenderId: '1014566436831',
    projectId: 'ecat-preparation',
    databaseURL: 'https://ecat-preparation-default-rtdb.firebaseio.com',
    storageBucket: 'ecat-preparation.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAVQxgZJ9NHLzax8GYg7R1kvbjvSMIgOX4',
    appId: '1:1014566436831:ios:a1908cdc4ab6dcfb7d8e6a',
    messagingSenderId: '1014566436831',
    projectId: 'ecat-preparation',
    databaseURL: 'https://ecat-preparation-default-rtdb.firebaseio.com',
    storageBucket: 'ecat-preparation.appspot.com',
    iosBundleId: 'com.example.e',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAVQxgZJ9NHLzax8GYg7R1kvbjvSMIgOX4',
    appId: '1:1014566436831:ios:a1908cdc4ab6dcfb7d8e6a',
    messagingSenderId: '1014566436831',
    projectId: 'ecat-preparation',
    databaseURL: 'https://ecat-preparation-default-rtdb.firebaseio.com',
    storageBucket: 'ecat-preparation.appspot.com',
    iosBundleId: 'com.example.e',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCEr6cJ1sDcna0P-mW0w1m2W1w5lPLKdak',
    appId: '1:1014566436831:web:5734cff9b0135e6c7d8e6a',
    messagingSenderId: '1014566436831',
    projectId: 'ecat-preparation',
    authDomain: 'ecat-preparation.firebaseapp.com',
    databaseURL: 'https://ecat-preparation-default-rtdb.firebaseio.com',
    storageBucket: 'ecat-preparation.appspot.com',
    measurementId: 'G-XH61KG06RG',
  );
}
